### ISSUE TITLE
Add a license file

### ISSUE THREAD

**Issue by Aprillion** [borismus/DevTools-Lab#1]
3rd and 4th result for https://www.google.com/search?q=chrome+devtools+cheat+sheet both contain the cheatsheet from this repo and I would like to use it for a training, but the screenshots are quite outdated...

@paulirish or @borismus is there some updated version not in this repository plz?

if not, do you want a pull request if I update it myself? http://smus.com/devtools-cheatsheet/ from 2011 points directly to the master branch, so would get automatically updated on merge, not sure if that would be GOOD or BAD for you...

could you plz add LICENSE file to this repo or to the blog itself to make it clear if people can print it as handouts for (noncommercial?) workshops?

**Comment by borismus** [comment]
Added a license (COPYING). This is quite old and I don't think used much. If you want to fork and submit PR with updated screenshots, will be thankful.

**Comment by Aprillion** [comment]
We decided to just give people link to official docs which are very good: https://developers.google.com/web/tools/chrome-devtools/

No printed handouts => I am not going to update at this time.

Thanks for adding the license!
